// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPwhuYtOfXWNWaXjtS5eyEx33COs6w5d0',
    appId: '1:637000729210:web:b4f1e03a9426d99ace71c3',
    messagingSenderId: '637000729210',
    projectId: 'etask-mobile',
    authDomain: 'etask-mobile.firebaseapp.com',
    databaseURL: 'https://etask-mobile.firebaseio.com',
    storageBucket: 'etask-mobile.firebasestorage.app',
    measurementId: 'G-FRYSQ8HDZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuJUgpgt2AvETJPd6hU5CtWi-YwT3vHFU',
    appId: '1:637000729210:android:5187ec203ce8b44bce71c3',
    messagingSenderId: '637000729210',
    projectId: 'etask-mobile',
    databaseURL: 'https://etask-mobile.firebaseio.com',
    storageBucket: 'etask-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl4NLadR_ypukronUN7sS4ioVITP70saw',
    appId: '1:637000729210:ios:07560f127496d5c7ce71c3',
    messagingSenderId: '637000729210',
    projectId: 'etask-mobile',
    databaseURL: 'https://etask-mobile.firebaseio.com',
    storageBucket: 'etask-mobile.firebasestorage.app',
    iosBundleId: 'com.appvity.ptth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl4NLadR_ypukronUN7sS4ioVITP70saw',
    appId: '1:637000729210:ios:07560f127496d5c7ce71c3',
    messagingSenderId: '637000729210',
    projectId: 'etask-mobile',
    databaseURL: 'https://etask-mobile.firebaseio.com',
    storageBucket: 'etask-mobile.firebasestorage.app',
    iosBundleId: 'com.appvity.ptth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPwhuYtOfXWNWaXjtS5eyEx33COs6w5d0',
    appId: '1:637000729210:web:2bbaf474a687341ace71c3',
    messagingSenderId: '637000729210',
    projectId: 'etask-mobile',
    authDomain: 'etask-mobile.firebaseapp.com',
    databaseURL: 'https://etask-mobile.firebaseio.com',
    storageBucket: 'etask-mobile.firebasestorage.app',
    measurementId: 'G-5V2ZWBEPYC',
  );

}